name = "late-records-pricer-bouncer"
main = "index.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "late-records.shop/pricer.html"
zone_name = "late-records.shop"

[assets]
directory = "../site"
binding = "ASSETS"